/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as QrPixRouteImport } from './routes/qr-pix'
import { Route as PerfisRouteImport } from './routes/perfis'
import { Route as PalavraRouteImport } from './routes/palavra'
import { Route as LogomarcaRouteImport } from './routes/logomarca'
import { Route as HorasRouteImport } from './routes/horas'
import { Route as FontesRouteImport } from './routes/fontes'
import { Route as IndexRouteImport } from './routes/index'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const QrPixRoute = QrPixRouteImport.update({
  id: '/qr-pix',
  path: '/qr-pix',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfisRoute = PerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => rootRouteImport,
} as any)
const PalavraRoute = PalavraRouteImport.update({
  id: '/palavra',
  path: '/palavra',
  getParentRoute: () => rootRouteImport,
} as any)
const LogomarcaRoute = LogomarcaRouteImport.update({
  id: '/logomarca',
  path: '/logomarca',
  getParentRoute: () => rootRouteImport,
} as any)
const HorasRoute = HorasRouteImport.update({
  id: '/horas',
  path: '/horas',
  getParentRoute: () => rootRouteImport,
} as any)
const FontesRoute = FontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fontes': typeof FontesRoute
  '/horas': typeof HorasRoute
  '/logomarca': typeof LogomarcaRoute
  '/palavra': typeof PalavraRoute
  '/perfis': typeof PerfisRoute
  '/qr-pix': typeof QrPixRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fontes': typeof FontesRoute
  '/horas': typeof HorasRoute
  '/logomarca': typeof LogomarcaRoute
  '/palavra': typeof PalavraRoute
  '/perfis': typeof PerfisRoute
  '/qr-pix': typeof QrPixRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fontes': typeof FontesRoute
  '/horas': typeof HorasRoute
  '/logomarca': typeof LogomarcaRoute
  '/palavra': typeof PalavraRoute
  '/perfis': typeof PerfisRoute
  '/qr-pix': typeof QrPixRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fontes'
    | '/horas'
    | '/logomarca'
    | '/palavra'
    | '/perfis'
    | '/qr-pix'
    | '/suporte'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fontes'
    | '/horas'
    | '/logomarca'
    | '/palavra'
    | '/perfis'
    | '/qr-pix'
    | '/suporte'
  id:
    | '__root__'
    | '/'
    | '/fontes'
    | '/horas'
    | '/logomarca'
    | '/palavra'
    | '/perfis'
    | '/qr-pix'
    | '/suporte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FontesRoute: typeof FontesRoute
  HorasRoute: typeof HorasRoute
  LogomarcaRoute: typeof LogomarcaRoute
  PalavraRoute: typeof PalavraRoute
  PerfisRoute: typeof PerfisRoute
  QrPixRoute: typeof QrPixRoute
  SuporteRoute: typeof SuporteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-pix': {
      id: '/qr-pix'
      path: '/qr-pix'
      fullPath: '/qr-pix'
      preLoaderRoute: typeof QrPixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfis': {
      id: '/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof PerfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palavra': {
      id: '/palavra'
      path: '/palavra'
      fullPath: '/palavra'
      preLoaderRoute: typeof PalavraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logomarca': {
      id: '/logomarca'
      path: '/logomarca'
      fullPath: '/logomarca'
      preLoaderRoute: typeof LogomarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horas': {
      id: '/horas'
      path: '/horas'
      fullPath: '/horas'
      preLoaderRoute: typeof HorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fontes': {
      id: '/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FontesRoute: FontesRoute,
  HorasRoute: HorasRoute,
  LogomarcaRoute: LogomarcaRoute,
  PalavraRoute: PalavraRoute,
  PerfisRoute: PerfisRoute,
  QrPixRoute: QrPixRoute,
  SuporteRoute: SuporteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
