/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogomarcaRouteImport } from './routes/logomarca'
import { Route as FontesRouteImport } from './routes/fontes'
import { Route as IndexRouteImport } from './routes/index'

const LogomarcaRoute = LogomarcaRouteImport.update({
  id: '/logomarca',
  path: '/logomarca',
  getParentRoute: () => rootRouteImport,
} as any)
const FontesRoute = FontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fontes': typeof FontesRoute
  '/logomarca': typeof LogomarcaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fontes': typeof FontesRoute
  '/logomarca': typeof LogomarcaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fontes': typeof FontesRoute
  '/logomarca': typeof LogomarcaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fontes' | '/logomarca'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fontes' | '/logomarca'
  id: '__root__' | '/' | '/fontes' | '/logomarca'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FontesRoute: typeof FontesRoute
  LogomarcaRoute: typeof LogomarcaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logomarca': {
      id: '/logomarca'
      path: '/logomarca'
      fullPath: '/logomarca'
      preLoaderRoute: typeof LogomarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fontes': {
      id: '/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FontesRoute: FontesRoute,
  LogomarcaRoute: LogomarcaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
