/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PalavraRouteImport } from './routes/palavra'
import { Route as LogomarcaRouteImport } from './routes/logomarca'
import { Route as HorasRouteImport } from './routes/horas'
import { Route as FontesRouteImport } from './routes/fontes'
import { Route as IndexRouteImport } from './routes/index'

const PalavraRoute = PalavraRouteImport.update({
  id: '/palavra',
  path: '/palavra',
  getParentRoute: () => rootRouteImport,
} as any)
const LogomarcaRoute = LogomarcaRouteImport.update({
  id: '/logomarca',
  path: '/logomarca',
  getParentRoute: () => rootRouteImport,
} as any)
const HorasRoute = HorasRouteImport.update({
  id: '/horas',
  path: '/horas',
  getParentRoute: () => rootRouteImport,
} as any)
const FontesRoute = FontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fontes': typeof FontesRoute
  '/horas': typeof HorasRoute
  '/logomarca': typeof LogomarcaRoute
  '/palavra': typeof PalavraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fontes': typeof FontesRoute
  '/horas': typeof HorasRoute
  '/logomarca': typeof LogomarcaRoute
  '/palavra': typeof PalavraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fontes': typeof FontesRoute
  '/horas': typeof HorasRoute
  '/logomarca': typeof LogomarcaRoute
  '/palavra': typeof PalavraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fontes' | '/horas' | '/logomarca' | '/palavra'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fontes' | '/horas' | '/logomarca' | '/palavra'
  id: '__root__' | '/' | '/fontes' | '/horas' | '/logomarca' | '/palavra'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FontesRoute: typeof FontesRoute
  HorasRoute: typeof HorasRoute
  LogomarcaRoute: typeof LogomarcaRoute
  PalavraRoute: typeof PalavraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/palavra': {
      id: '/palavra'
      path: '/palavra'
      fullPath: '/palavra'
      preLoaderRoute: typeof PalavraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logomarca': {
      id: '/logomarca'
      path: '/logomarca'
      fullPath: '/logomarca'
      preLoaderRoute: typeof LogomarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horas': {
      id: '/horas'
      path: '/horas'
      fullPath: '/horas'
      preLoaderRoute: typeof HorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fontes': {
      id: '/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FontesRoute: FontesRoute,
  HorasRoute: HorasRoute,
  LogomarcaRoute: LogomarcaRoute,
  PalavraRoute: PalavraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
